import pytest

import src.tts
from src.item.data.affix import Affix, AffixType
from src.item.data.aspect import Aspect
from src.item.data.item_type import ItemType
from src.item.data.rarity import ItemRarity
from src.item.descr.read_descr_tts import read_descr
from src.item.models import Item

items = [
    (
        # Sanctified items intentionally do not have their affixes read, which we are confirming with these next two tests
        [
            "ARCHON GAUNTLETS OF INFESTATION",
            "Ancestral Legendary Gloves",
            "800 Item Power",
            "[PH] 20 (+20) Quality",
            "Sanctified",
            "905 Armor",
            "+118 Dexterity +[107 - 121]",
            "+342 Life On Kill",
            "+97.5% Overpower Damage",
            "+451 Fire Resistance [441 - 490]",
            "+54 All Stats +[51 - 65]",
            "Lucky Hit: Centipede Skills have up to a 35% chance to spawn a Pestilent Swarm from the target which deals 436 [228 - 488] Poison damage per hit.. Pestilent Swarms now also deal 100% of their Base damage as Poisoning damage over 6 seconds.",
            "+14.2% Critical Strike Damage [12.0 - 15.0]%",
            "Requires Level 60. Account Bound. Vessel of Hatred Item",
            "Unmodifiable",
            "Sell Value: 19,254 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Gloves,
            name="archon_gauntlets_of_infestation",
            power=800,
            rarity=ItemRarity.Legendary,
            sanctified=True,
        ),
    ),
    (
        [
            "ASCENDANT QUARTERSTAFF OF UNYIELDING HITS",
            "Ancestral Legendary Quarterstaff",
            "800 Item Power",
            "Sanctified",
            "596 Damage Per Second",
            "[434 - 650] Damage per Hit",
            "1.10 Attacks per Second (Fast)",
            "45% Block Chance [45]%",
            "+231 Dexterity +[214 - 242]",
            "+1,370 Maximum Life",
            "+292 Life On Hit [292 - 318]",
            "+114.0% Overpower Damage [110.0 - 130.0]%",
            "Ignore Durability Loss",
            "Casting a Gorilla Skill increases your Weapon Damage by 52% [20 - 60]% of your Armor for 3 seconds. Maximum 1,500 bonus Weapon Damage.",
            "Empty Socket",
            "Requires Level 60. Account Bound. Only. Vessel of Hatred Item",
            "Unmodifiable",
            "Sell Value: 52,949 Gold",
            "Durability: Indestructible",
            "Mousewheel scroll down",
            "Scroll Down",
            "Right mouse button",
        ],
        Item(
            affixes=[],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Quarterstaff,
            name="ascendant_quarterstaff_of_unyielding_hits",
            power=800,
            rarity=ItemRarity.Legendary,
            sanctified=True,
        ),
    ),
    (
        [
            "ACCELERATING BONESCALE SHIELD",
            "Legendary Shield",
            "750 Item Power",
            "844 Armor (-22.7% Toughness)",
            "41% Blocked Damage Reduction [41]% (+41%)",
            "20% Block Chance [20]% (+20%)",
            "+100% Main Hand Weapon Damage [100]% (+100%)",
            "+261 Maximum Life [244 - 272] (-1,109)",
            "+1 Essence On Kill +[1] (+1)",
            "+10.0% Fortify Generation [7.0 - 12.0]% (+10.0%)",
            "+322 Lightning Resistance [321 - 350] (+322)",
            "Critical Strikes with Core Skills increase your Attack Speed by 18.0%[+] [10.0 - 25.0]% for 5 seconds.",
            "Properties lost when equipped:",
            "+2 to Finality",
            "+188.0% Critical Strike Damage",
            "+124.0% Shadow Damage",
            "+236 Intelligence",
            "Legendary Power",
            "Socket (2)",
            "Requires Level 60",
            "Sell Value: 23,647 Gold",
            "Durability: 100/100. Tempers: 3/3",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=272.0,
                    min_value=244.0,
                    name="maximum_life",
                    text="+261 Maximum Life [244 - 272] (-1,109)",
                    type=AffixType.normal,
                    value=261.0,
                ),
                Affix(
                    max_value=1.0,
                    min_value=1.0,
                    name="essence_on_kill",
                    text="+1 Essence On Kill +[1] (+1)",
                    type=AffixType.normal,
                    value=1.0,
                ),
                Affix(
                    max_value=12.0,
                    min_value=7.0,
                    name="fortify_generation",
                    text="+10.0% Fortify Generation [7.0 - 12.0]% (+10.0%)",
                    type=AffixType.normal,
                    value=10.0,
                ),
                Affix(
                    max_value=350.0,
                    min_value=321.0,
                    name="lightning_resistance",
                    text="+322 Lightning Resistance [321 - 350] (+322)",
                    type=AffixType.normal,
                    value=322.0,
                ),
            ],
            aspect=Aspect(
                name="accelerating",
                min_value=None,
                max_value=None,
                text="Critical Strikes with Core Skills increase your Attack Speed by 18.0%[+] [10.0 - 25.0]% for 5 seconds.",
                value=None,
            ),
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[
                Affix(
                    max_value=41.0,
                    min_value=41.0,
                    name="blocked_damage_reduction",
                    text="41% Blocked Damage Reduction [41]% (+41%)",
                    type=AffixType.inherent,
                    value=41.0,
                ),
                Affix(
                    max_value=20.0,
                    min_value=20.0,
                    name="block_chance",
                    text="20% Block Chance [20]% (+20%)",
                    type=AffixType.inherent,
                    value=20.0,
                ),
                Affix(
                    max_value=100.0,
                    min_value=100.0,
                    name="main_hand_weapon_damage",
                    text="+100% Main Hand Weapon Damage [100]% (+100%)",
                    type=AffixType.inherent,
                    value=100.0,
                ),
            ],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Shield,
            name="accelerating_bonescale_shield",
            power=750,
            rarity=ItemRarity.Legendary,
            sanctified=False,
        ),
    ),
]


@pytest.mark.parametrize(("input_item", "expected_item"), items)
def test_items(input_item: list[str], expected_item: Item):
    src.tts.LAST_ITEM = input_item
    item = read_descr()
    assert item == expected_item
