import pytest

import src.tts
from src.item.data.affix import Affix, AffixType
from src.item.data.aspect import Aspect
from src.item.data.item_type import ItemType
from src.item.data.rarity import ItemRarity
from src.item.descr.read_descr_tts import read_descr
from src.item.models import Item

items = [
    # Unique with no greater affixes and weird inherents
    (
        [
            "THE MORTACRUX",
            "Unique Dagger",
            "750 Item Power",
            "261 Damage Per Second  (-334)",
            "[174 - 262] Damage per Hit",
            "1.20 Attacks per Second (Very Fast) (+0.30)",
            "+85.0% Macabre Damage [85.0]% (+85.0%)",
            "+85.0% Corpse Damage [85.0]% (+85.0%)",
            "+78 Intelligence +[73 - 83] (-157)",
            "+45.5% Chance for Corpse Explosion to Deal Double Damage [36.5 - 50.0]% (+45.5%)",
            "Hewed Flesh Grants 7.0% Maximum Life as Barrier for 4 Seconds [7.0 - 9.0]% (+7.0%)",
            "+2 to Hewed Flesh [2 - 4] (+2)",
            "When consuming a Corpse, there is a 26% [20 - 40]% chance to also create a decaying Skeletal Simulacrum that seeks enemies but cannot attack. When it dies, it explodes for 2,382 Shadow damage. . This effect is treated as a Macabre Skill.",
            "Empty Socket",
            "Properties lost when equipped:",
            "+874 Maximum Life",
            "+2 to Finality",
            "+512.7% Overpower Damage",
            "+205.0% Damage while Fortified",
            "Legendary Power",
            "Socket (1)",
            "One of a pair of twin daggers, forbidden from ever meeting. Nearby corpses shudder in its presence.",
            "Requires Level 60Necromancer. Only. Unique Equipped",
            "Unlocks new look on salvage",
            "Sell Value: 184,341 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=83,
                    min_value=73,
                    name="intelligence",
                    text="+78 Intelligence +[73 - 83] (-157)",
                    type=AffixType.normal,
                    value=78.0,
                ),
                Affix(
                    max_value=50.0,
                    min_value=36.5,
                    name="chance_for_corpse_explosion_to_deal_double_damage",
                    text="+45.5% Chance for Corpse Explosion to Deal Double Damage [36.5 - 50.0]% (+45.5%)",
                    type=AffixType.normal,
                    value=45.5,
                ),
                Affix(
                    max_value=9.0,
                    min_value=7.0,
                    name="hewed_flesh_grants_maximum_life_as_barrier_for_seconds",
                    text="Hewed Flesh Grants 7.0% Maximum Life as Barrier for 4 Seconds [7.0 - 9.0]% (+7.0%)",
                    type=AffixType.normal,
                    value=7.0,
                ),
                Affix(
                    max_value=4,
                    min_value=2,
                    name="to_hewed_flesh",
                    text="+2 to Hewed Flesh [2 - 4] (+2)",
                    type=AffixType.normal,
                    value=2.0,
                ),
            ],
            aspect=Aspect(
                name="the_mortacrux",
                text="When consuming a Corpse, there is a 26% [20 - 40]% chance to also create a decaying Skeletal Simulacrum that seeks enemies but cannot attack. When it dies, it explodes for 2,382 Shadow damage. . This effect is treated as a Macabre Skill.",
                value=26,
            ),
            codex_upgrade=False,
            cosmetic_upgrade=True,
            inherent=[
                Affix(
                    max_value=85,
                    min_value=85,
                    name="macabre_damage",
                    text="+85.0% Macabre Damage [85.0]% (+85.0%)",
                    type=AffixType.inherent,
                    value=85.0,
                ),
                Affix(
                    max_value=85,
                    min_value=85,
                    name="corpse_damage",
                    text="+85.0% Corpse Damage [85.0]% (+85.0%)",
                    type=AffixType.inherent,
                    value=85.0,
                ),
            ],
            item_type=ItemType.Dagger,
            name="the_mortacrux",
            power=750,
            rarity=ItemRarity.Unique,
        ),
    ),
    # Unique with GA
    (
        [
            "SHARD OF VERATHIEL",
            "Ancestral Unique Sword",
            "800 Item Power",
            "298 Damage Per Second  (-297)",
            "[217 - 325] Damage per Hit",
            "1.10 Attacks per Second (Fast) (+0.20)",
            "+50.0% Damage [50.0]% (+50.0%)",
            "+56 All Stats +[51 - 65] (+56)",
            "+24 Maximum Resource (+24)",
            "+18.0% Basic Attack Speed [16.0 - 25.0]% (+18.0%)",
            "+2 to Basic Skills [1 - 2] (+2)",
            "Basic Skills deal 133%[x] [50 - 200]% increased damage but additionally cost 25 Primary Resource.",
            "Empty Socket",
            "Properties lost when equipped:",
            "+874 Maximum Life",
            "+2 to Finality",
            "+512.7% Overpower Damage",
            "+205.0% Damage while Fortified",
            "+235 Intelligence",
            "Legendary Power",
            "Socket (1)",
            "This blade once bore divine purpose wielded by the angel Verathiel. Like its keeper, the sword fell to Infernal depths. Yet beneath this corruption, is a heartbeat of a past memory, holding steadfast.",
            "Requires Level 60. Unique Equipped",
            "Sell Value: 206,382 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=65.0,
                    min_value=51.0,
                    name="all_stats",
                    text="+56 All Stats +[51 - 65] (+56)",
                    type=AffixType.normal,
                    value=56.0,
                ),
                Affix(
                    max_value=None,
                    min_value=None,
                    name="maximum_resource",
                    text="+24 Maximum Resource (+24)",
                    type=AffixType.greater,
                    value=24.0,
                ),
                Affix(
                    max_value=25.0,
                    min_value=16.0,
                    name="basic_attack_speed",
                    text="+18.0% Basic Attack Speed [16.0 - 25.0]% (+18.0%)",
                    type=AffixType.normal,
                    value=18.0,
                ),
                Affix(
                    max_value=2.0,
                    min_value=1.0,
                    name="to_basic_skills",
                    text="+2 to Basic Skills [1 - 2] (+2)",
                    type=AffixType.normal,
                    value=2.0,
                ),
            ],
            aspect=Aspect(
                name="shard_of_verathiel",
                text="Basic Skills deal 133%[x] [50 - 200]% increased damage but additionally cost 25 Primary Resource.",
                value=133.0,
            ),
            codex_upgrade=False,
            inherent=[
                Affix(
                    max_value=50.0,
                    min_value=50.0,
                    name="damage",
                    text="+50.0% Damage [50.0]% (+50.0%)",
                    type=AffixType.inherent,
                    value=50.0,
                )
            ],
            item_type=ItemType.Sword,
            name="shard_of_verathiel",
            power=800,
            rarity=ItemRarity.Unique,
        ),
    ),
    # Another unique incorrectly parsing a GA
    (
        [
            "FROSTBURN",
            "Unique Gloves",
            "750 Item Power",
            "60 Armor",
            "+7.0% Lucky Hit Chance [7.0]%",
            "+12.0% Attack Speed [8.0 - 12.5]% (+12.0%)",
            "+124.0% Fire and Cold Damage [124.0 - 160.0]% (+124.0%)",
            "Lucky Hit: Up to a 40% Chance to Deal +650 Fire Damage [600 - 1,000] (+650)",
            "Lucky Hit: Up to a 40% Chance to Deal +1,000 Cold Damage [600 - 1,000] (+1,000)",
            "Lucky Hit: Up to a 40% [20 - 60]% chance to Freeze enemies for 3 seconds.",
            "Properties lost when equipped:",
            "+144.5% Blood Overpower Damage",
            "+35.5% Corpse Tendrils Size",
            "+98 Intelligence",
            "+6.8% Critical Strike Chance",
            "Legendary Power",
            "A touch so frigid it stops the heart and chills the very soul.",
            "Requires Level 60. Unique Equipped",
            "Sell Value: 90,289 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=12.5,
                    min_value=8.0,
                    name="attack_speed",
                    text="+12.0% Attack Speed [8.0 - 12.5]% (+12.0%)",
                    type=AffixType.normal,
                    value=12.0,
                ),
                Affix(
                    max_value=160.0,
                    min_value=124.0,
                    name="fire_and_cold_damage",
                    text="+124.0% Fire and Cold Damage [124.0 - 160.0]% (+124.0%)",
                    type=AffixType.normal,
                    value=124.0,
                ),
                Affix(
                    max_value=1000,
                    min_value=600,
                    name="lucky_hit_up_to_a_chance_to_deal_fire_damage",
                    text="Lucky Hit: Up to a 40% Chance to Deal +650 Fire Damage [600 - 1,000] (+650)",
                    type=AffixType.normal,
                    value=650.0,
                ),
                Affix(
                    max_value=1000,
                    min_value=600,
                    name="lucky_hit_up_to_a_chance_to_deal_cold_damage",
                    text="Lucky Hit: Up to a 40% Chance to Deal +1,000 Cold Damage [600 - 1,000] (+1,000)",
                    type=AffixType.normal,
                    value=1000.0,
                ),
            ],
            aspect=Aspect(name="frostburn", text="Lucky Hit: Up to a 40% [20 - 60]% chance to Freeze enemies for 3 seconds.", value=40.0),
            codex_upgrade=False,
            inherent=[
                Affix(
                    max_value=7.0,
                    min_value=7.0,
                    name="lucky_hit_chance",
                    text="+7.0% Lucky Hit Chance [7.0]%",
                    type=AffixType.inherent,
                    value=7.0,
                )
            ],
            item_type=ItemType.Gloves,
            name="frostburn",
            power=750,
            rarity=ItemRarity.Unique,
        ),
    ),
    (
        [
            "BLOOD ARTISANS CUIRASS",
            "Unique Chest Armor",
            "750 Item Power",
            "210 Armor",
            "+305 Maximum Life [305 - 340]",
            "+125.0% Damage for 4 Seconds After Picking Up a Blood Orb [98.0 - 125.0]%[4]",
            "Blood Orbs Restore +9 Essence [8 - 12]",
            "+3 to Bone Spirit [2 - 3]",
            "When you pick up 5 [10 - 3] Blood Orbs, a free Bone Spirit is spawned, dealing bonus damage based on your current Life percent.",
            "Empty Socket",
            "The infamous Necromancer Gaza-Thuls mastery over blood magic was indisputable. Many suspect that upon his death, his skin was used to fashion this eldritch armor.. - Barretts Book of Implements",
            "Requires Level 60Necromancer. Only. Unique Equipped",
            "Sell Value: 184,341 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=340.0,
                    min_value=305.0,
                    name="maximum_life",
                    text="+305 Maximum Life [305 - 340]",
                    type=AffixType.normal,
                    value=305.0,
                ),
                Affix(
                    max_value=125.0,
                    min_value=98.0,
                    name="damage_for_seconds_after_picking_up_a_blood_orb",
                    text="+125.0% Damage for 4 Seconds After Picking Up a Blood Orb [98.0 - 125.0]%[4]",
                    type=AffixType.normal,
                    value=125.0,
                ),
                Affix(
                    max_value=12.0,
                    min_value=8.0,
                    name="blood_orbs_restore_essence",
                    text="Blood Orbs Restore +9 Essence [8 - 12]",
                    type=AffixType.normal,
                    value=9.0,
                ),
                Affix(
                    max_value=3.0,
                    min_value=2.0,
                    name="to_bone_spirit",
                    text="+3 to Bone Spirit [2 - 3]",
                    type=AffixType.normal,
                    value=3.0,
                ),
            ],
            aspect=Aspect(
                name="blood_artisans_cuirass",
                text="When you pick up 5 [10 - 3] Blood Orbs, a free Bone Spirit is spawned, dealing bonus damage based on your current Life percent.",
                value=5.0,
            ),
            codex_upgrade=False,
            inherent=[],
            item_type=ItemType.ChestArmor,
            name="blood_artisans_cuirass",
            power=750,
            rarity=ItemRarity.Unique,
        ),
    ),
    # Ensuring mythics are read correctly
    (
        [
            "HARLEQUIN CREST",
            "Ancestral Mythic Unique Helm",
            "800 Item Power",
            "Masterwork: 12 / 12",
            "128 Armor",
            "+1,760 Maximum Life [1,760]",
            "+26 Maximum Resource [26]",
            "+682 Armor",
            "29.0% Cooldown Reduction [29.0]%",
            "Gain 20% Damage Reduction. In addition, gain +4 Ranks to all Skills.",
            "+60 Intelligence",
            "+40 Intelligence",
            "This headdress was once worn by an assassin disguised as a court mage. Her treachery was unveiled, but not before she used its magic to curse the kings entire lineage.. - The Fall of House Aston",
            "Requires Level 35. Account Bound. Unique Equipped",
            "Sell Value: 164,263 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=1760.0,
                    min_value=1760.0,
                    name="maximum_life",
                    text="+1,760 Maximum Life [1,760]",
                    type=AffixType.normal,
                    value=1760.0,
                ),
                Affix(
                    max_value=26.0,
                    min_value=26.0,
                    name="maximum_resource",
                    text="+26 Maximum Resource [26]",
                    type=AffixType.normal,
                    value=26.0,
                ),
                Affix(max_value=None, min_value=None, name="armor", text="+682 Armor", type=AffixType.greater, value=682.0),
                Affix(
                    max_value=29.0,
                    min_value=29.0,
                    name="cooldown_reduction",
                    text="29.0% Cooldown Reduction [29.0]%",
                    type=AffixType.normal,
                    value=29.0,
                ),
            ],
            aspect=Aspect(name="harlequin_crest", text="Gain 20% Damage Reduction. In addition, gain +4 Ranks to all Skills.", value=20.0),
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            item_type=ItemType.Helm,
            name="harlequin_crest",
            power=800,
            rarity=ItemRarity.Mythic,
        ),
    ),
    # A real strange inherent that isn't matching its affix for some reason, though the affix exists
    (
        [
            "SCOUNDRELS LEATHERS",
            "Ancestral Unique Chest Armor",
            "800 Item Power",
            "Masterwork: 8 / 12",
            "Armory Loadout",
            "224 Armor",
            "Your Trap and Grenade Skills are also considered Core Skills",
            "+847 Maximum Life [822 - 885]",
            "+33.8% Movement Speed while the Inner Sight Gauge is Full [33.8 - 45.5]%",
            "+42.9% Inner Sight Duration [40.9 - 58.5]%",
            "30.8% Damage Reduction from Enemies Affected by Trap Skills",
            "While you have unlimited Energy from Inner Sight, casting a Core Skill has a 80% [60 - 80]% chance to spawn Caltrops, Poison Trap, or Death Trap. Gain 20%[x] [10 - 20]% Core Skill Damage.",
            "+40 Dexterity",
            "+40 Dexterity",
            "Rumor has it he lost them in a game of Skull &amp; Anchor, but the boss is a devil with the dice. I think he wanted to give the poor sod something to keep him warm without wounding his pride.. - Elstir",
            "Requires Level 60. Account BoundRogue. Only. Unique Equipped",
            "Sell Value: 219,018 Gold",
            "Durability: 60/100",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=885.0,
                    min_value=822.0,
                    name="maximum_life",
                    text="+847 Maximum Life [822 - 885]",
                    type=AffixType.normal,
                    value=847.0,
                ),
                Affix(
                    max_value=45.5,
                    min_value=33.8,
                    name="movement_speed_while_the_inner_sight_gauge_is_full",
                    text="+33.8% Movement Speed while the Inner Sight Gauge is Full [33.8 - 45.5]%",
                    type=AffixType.normal,
                    value=33.8,
                ),
                Affix(
                    max_value=58.5,
                    min_value=40.9,
                    name="inner_sight_duration",
                    text="+42.9% Inner Sight Duration [40.9 - 58.5]%",
                    type=AffixType.normal,
                    value=42.9,
                ),
                Affix(
                    max_value=None,
                    min_value=None,
                    name="damage_reduction_from_enemies_affected_by_trap_skills",
                    text="30.8% Damage Reduction from Enemies Affected by Trap Skills",
                    type=AffixType.greater,
                    value=30.8,
                ),
            ],
            aspect=Aspect(
                name="scoundrels_leathers",
                min_value=60.0,
                max_value=80.0,
                text="While you have unlimited Energy from Inner Sight, "
                "casting a Core Skill has a 80% [60 - 80]% chance to "
                "spawn Caltrops, Poison Trap, or Death Trap. Gain "
                "20%[x] [10 - 20]% Core Skill Damage.",
                value=80.0,
            ),
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[
                Affix(
                    max_value=None,
                    min_value=None,
                    name="your_trap_skills_are_also_considered_core_skills",
                    text="Your Trap and Grenade Skills are also considered Core Skills",
                    type=AffixType.inherent,
                    value=None,
                )
            ],
            item_type=ItemType.ChestArmor,
            name="scoundrels_leathers",
            power=800,
            rarity=ItemRarity.Unique,
        ),
    ),
]


@pytest.mark.parametrize(("input_item", "expected_item"), items)
def test_items(input_item: list[str], expected_item: Item):
    src.tts.LAST_ITEM = input_item
    item = read_descr()
    assert item == expected_item
