import pytest

import src.tts
from src.item.data.affix import Affix, AffixType
from src.item.data.aspect import Aspect
from src.item.data.item_type import ItemType
from src.item.data.rarity import ItemRarity
from src.item.descr.read_descr_tts import read_descr
from src.item.models import Item

items = [
    (
        # Sanctified items intentionally do not have their affixes read, which we are confirming with these next two tests
        [
            "ARCHON GAUNTLETS OF INFESTATION",
            "Ancestral Legendary Gloves",
            "800 Item Power",
            "[PH] 20 (+20) Quality",
            "Sanctified",
            "905 Armor",
            "+118 Dexterity +[107 - 121]",
            "+342 Life On Kill",
            "+97.5% Overpower Damage",
            "+451 Fire Resistance [441 - 490]",
            "+54 All Stats +[51 - 65]",
            "Lucky Hit: Centipede Skills have up to a 35% chance to spawn a Pestilent Swarm from the target which deals 436 [228 - 488] Poison damage per hit.. Pestilent Swarms now also deal 100% of their Base damage as Poisoning damage over 6 seconds.",
            "+14.2% Critical Strike Damage [12.0 - 15.0]%",
            "Requires Level 60. Account Bound. Vessel of Hatred Item",
            "Unmodifiable",
            "Sell Value: 19,254 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Gloves,
            name="archon_gauntlets_of_infestation",
            power=800,
            rarity=ItemRarity.Legendary,
            sanctified=True,
        ),
    ),
    (
        [
            "ASCENDANT QUARTERSTAFF OF UNYIELDING HITS",
            "Ancestral Legendary Quarterstaff",
            "800 Item Power",
            "Sanctified",
            "596 Damage Per Second",
            "[434 - 650] Damage per Hit",
            "1.10 Attacks per Second (Fast)",
            "45% Block Chance [45]%",
            "+231 Dexterity +[214 - 242]",
            "+1,370 Maximum Life",
            "+292 Life On Hit [292 - 318]",
            "+114.0% Overpower Damage [110.0 - 130.0]%",
            "Ignore Durability Loss",
            "Casting a Gorilla Skill increases your Weapon Damage by 52% [20 - 60]% of your Armor for 3 seconds. Maximum 1,500 bonus Weapon Damage.",
            "Empty Socket",
            "Requires Level 60. Account Bound. Only. Vessel of Hatred Item",
            "Unmodifiable",
            "Sell Value: 52,949 Gold",
            "Durability: Indestructible",
            "Mousewheel scroll down",
            "Scroll Down",
            "Right mouse button",
        ],
        Item(
            affixes=[],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Quarterstaff,
            name="ascendant_quarterstaff_of_unyielding_hits",
            power=800,
            rarity=ItemRarity.Legendary,
            sanctified=True,
        ),
    ),
    (
        [
            "ACCELERATING BONESCALE SHIELD",
            "Legendary Shield",
            "750 Item Power",
            "844 Armor (-22.7% Toughness)",
            "41% Blocked Damage Reduction [41]% (+41%)",
            "20% Block Chance [20]% (+20%)",
            "+100% Main Hand Weapon Damage [100]% (+100%)",
            "+261 Maximum Life [244 - 272] (-1,109)",
            "+1 Essence On Kill +[1] (+1)",
            "+10.0% Fortify Generation [7.0 - 12.0]% (+10.0%)",
            "+322 Lightning Resistance [321 - 350] (+322)",
            "Critical Strikes with Core Skills increase your Attack Speed by 18.0%[+] [10.0 - 25.0]% for 5 seconds.",
            "Properties lost when equipped:",
            "+2 to Finality",
            "+188.0% Critical Strike Damage",
            "+124.0% Shadow Damage",
            "+236 Intelligence",
            "Legendary Power",
            "Socket (2)",
            "Requires Level 60",
            "Sell Value: 23,647 Gold",
            "Durability: 100/100. Tempers: 3/3",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=272.0,
                    min_value=244.0,
                    name="maximum_life",
                    text="+261 Maximum Life [244 - 272] (-1,109)",
                    type=AffixType.normal,
                    value=261.0,
                ),
                Affix(
                    max_value=1.0,
                    min_value=1.0,
                    name="essence_on_kill",
                    text="+1 Essence On Kill +[1] (+1)",
                    type=AffixType.normal,
                    value=1.0,
                ),
                Affix(
                    max_value=12.0,
                    min_value=7.0,
                    name="fortify_generation",
                    text="+10.0% Fortify Generation [7.0 - 12.0]% (+10.0%)",
                    type=AffixType.normal,
                    value=10.0,
                ),
                Affix(
                    max_value=350.0,
                    min_value=321.0,
                    name="lightning_resistance",
                    text="+322 Lightning Resistance [321 - 350] (+322)",
                    type=AffixType.normal,
                    value=322.0,
                ),
            ],
            aspect=Aspect(
                name="accelerating",
                min_value=None,
                max_value=None,
                text="Critical Strikes with Core Skills increase your Attack Speed by 18.0%[+] [10.0 - 25.0]% for 5 seconds.",
                value=None,
            ),
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[
                Affix(
                    max_value=41.0,
                    min_value=41.0,
                    name="blocked_damage_reduction",
                    text="41% Blocked Damage Reduction [41]% (+41%)",
                    type=AffixType.inherent,
                    value=41.0,
                ),
                Affix(
                    max_value=20.0,
                    min_value=20.0,
                    name="block_chance",
                    text="20% Block Chance [20]% (+20%)",
                    type=AffixType.inherent,
                    value=20.0,
                ),
                Affix(
                    max_value=100.0,
                    min_value=100.0,
                    name="main_hand_weapon_damage",
                    text="+100% Main Hand Weapon Damage [100]% (+100%)",
                    type=AffixType.inherent,
                    value=100.0,
                ),
            ],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Shield,
            name="accelerating_bonescale_shield",
            power=750,
            rarity=ItemRarity.Legendary,
            sanctified=False,
        ),
    ),
    # Item from another class
    (
        [
            "BONEWEAVE GAUNTLETS OF CELESTIAL STRIFE",
            "Legendary Gloves",
            "750 Item Power",
            "562 Armor (+15.4% Toughness)",
            "+90 Strength +[89 - 99] (Barbarian  Only)",
            "+7.0% Critical Strike Chance [6.0 - 7.0]% (+7.0%)",
            "+39.0% Vulnerable Damage [35.0 - 45.0]% (+39.0%)",
            "+340 Lightning Resistance [321 - 350] (+340)",
            "While in Arbiter, kills grant 1.5%[x] [1.5 - 2.3]% increased Vulnerable damage, up to a maximum of 75%[x] [75 - 113]%. ( Only)",
            "Properties lost when equipped:",
            "1.9% Resource Cost Reduction",
            "2.0% Cooldown Reduction",
            "+2 Life On Hit",
            "Requires Level 60. Lord of Hatred Item",
            "Unlocks new Aspect in the Codex of Power on salvage",
            "Sell Value: 17,198 Gold",
            "Durability: 100/100. Tempers: 3/3",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=99.0,
                    min_value=89.0,
                    name="strength",
                    text="+90 Strength +[89 - 99] (Barbarian  Only)",
                    type=AffixType.normal,
                    value=90.0,
                ),
                Affix(
                    max_value=7.0,
                    min_value=6.0,
                    name="critical_strike_chance",
                    text="+7.0% Critical Strike Chance [6.0 - 7.0]% (+7.0%)",
                    type=AffixType.normal,
                    value=7.0,
                ),
                Affix(
                    max_value=45.0,
                    min_value=35.0,
                    name="vulnerable_damage",
                    text="+39.0% Vulnerable Damage [35.0 - 45.0]% (+39.0%)",
                    type=AffixType.normal,
                    value=39.0,
                ),
                Affix(
                    max_value=350.0,
                    min_value=321.0,
                    name="lightning_resistance",
                    text="+340 Lightning Resistance [321 - 350] (+340)",
                    type=AffixType.normal,
                    value=340.0,
                ),
            ],
            aspect=Aspect(
                name="of_celestial_strife",
                text="While in Arbiter, kills grant 1.5%[x] [1.5 - 2.3]% increased Vulnerable damage, up to a maximum of 75%[x] [75 - 113]%. ( Only)",
            ),
            codex_upgrade=True,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Gloves,
            name="boneweave_gauntlets_of_celestial_strife",
            power=750,
            rarity=ItemRarity.Legendary,
            sanctified=False,
        ),
    ),
    # 3 Affix rare that has been imprinted and turned into a legendary
    (
        [
            "SHEPHERDS DEATHLINGS EYELET",
            "Legendary Amulet",
            "495 Item Power",
            "91 All Resist",
            "+14 Maximum Life [12 - 15]",
            "+4.3% Critical Strike Chance [4.0 - 4.5]%",
            "3.0% Cooldown Reduction [3.0 - 3.4]%",
            "Imprinted: Companion Skills deal an additional 14.3%[x] [7.5 - 19.5]% damage per Companion you have.",
            "Empty Socket",
            "Requires Level 48. Account Bound",
            "Sell Value: 15,584 Gold",
            "Tempers: 3/3",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=15.0,
                    min_value=12.0,
                    name="maximum_life",
                    text="+14 Maximum Life [12 - 15]",
                    type=AffixType.normal,
                    value=14.0,
                ),
                Affix(
                    max_value=4.5,
                    min_value=4.0,
                    name="critical_strike_chance",
                    text="+4.3% Critical Strike Chance [4.0 - 4.5]%",
                    type=AffixType.normal,
                    value=4.3,
                ),
                Affix(
                    max_value=3.4,
                    min_value=3.0,
                    name="cooldown_reduction",
                    text="3.0% Cooldown Reduction [3.0 - 3.4]%",
                    type=AffixType.normal,
                    value=3.0,
                ),
            ],
            aspect=Aspect(
                name="shepherds",
                min_value=None,
                max_value=None,
                text="Imprinted: Companion Skills deal an additional 14.3%[x] [7.5 - 19.5]% damage per Companion you have.",
                value=None,
            ),
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Amulet,
            name="shepherds_deathlings_eyelet",
            power=495,
            rarity=ItemRarity.Legendary,
            sanctified=False,
        ),
    ),
    # Masterworked item so it has a quality indicator
    (
        [
            "LIMBIC BOUNDARY OF THE RABID BEAST",
            "Ancestral Legendary Ring",
            "800 Item Power",
            "25 ( +25) Quality",
            "204 All Resist",
            "+212 Willpower",
            "+555 Maximum Life [424 - 457]",
            "+7.5% Critical Strike Chance [5.2 - 6.0]%",
            "Lucky Hit: Up to a +54.1% Chance to Make Enemies Vulnerable for 2 Seconds [43.3 - 47.2]%[2]",
            "Imprinted: Deal 58%[x] [40 - 80]% more Poison damage. While Shapeshifted, your direct damage is converted into Poison damage.",
            "+125 Resistance to All Elements",
            "Requires Level 60. Account Bound",
            "Sell Value: 33,288 Gold",
            "Tempers: 4/4",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=None,
                    min_value=None,
                    name="willpower",
                    text="+212 Willpower",
                    type=AffixType.greater,
                    value=212.0,
                ),
                Affix(
                    max_value=457.0,
                    min_value=424.0,
                    name="maximum_life",
                    text="+555 Maximum Life [424 - 457]",
                    type=AffixType.normal,
                    value=555.0,
                ),
                Affix(
                    max_value=6.0,
                    min_value=5.2,
                    name="critical_strike_chance",
                    text="+7.5% Critical Strike Chance [5.2 - 6.0]%",
                    type=AffixType.normal,
                    value=7.5,
                ),
                Affix(
                    max_value=47.2,
                    min_value=43.3,
                    name="lucky_hit_up_to_a_chance_to_make_enemies_vulnerable_for_seconds",
                    text="Lucky Hit: Up to a +54.1% Chance to Make Enemies Vulnerable for 2 Seconds [43.3 - 47.2]%[2]",
                    type=AffixType.normal,
                    value=54.1,
                ),
            ],
            aspect=Aspect(
                name="of_the_rabid_beast",
                min_value=None,
                max_value=None,
                text="Imprinted: Deal 58%[x] [40 - 80]% more Poison damage. While Shapeshifted, your direct damage is converted into Poison damage.",
                value=None,
            ),
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Ring,
            name="limbic_boundary_of_the_rabid_beast",
            power=800,
            rarity=ItemRarity.Legendary,
            sanctified=False,
        ),
    ),
    # Escalation sigil that is also a whisper
    (
        [
            "HAUNTED REFUGE ESCALATION SIGIL",
            "Legendary Escalation Sigil",
            "Brave a series of dungeons, each one deadlier than the last, in search of Astaroths Lair.",
            "Haunted Refuge in Hawezar",
            "Grants Grim Favor for 17m",
            "AFFIXES",
            "Hidden Armory",
            "Exceptional items are kept here, granting elite monsters a powerful loot affix.",
            "Deathly Shadows",
            "Killing a monster has a chance to unleash a volatile pulse after a short delay, dealing heavy area damage.",
            "Account Bound",
            "Sell Value: 1 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(max_value=None, min_value=None, name="hidden_armory", text="", type=AffixType.normal, value=None),
                Affix(
                    max_value=None, min_value=None, name="deathly_shadows", text="", type=AffixType.normal, value=None
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.EscalationSigil,
            name="haunted_refuge",
            power=None,
            rarity=ItemRarity.Legendary,
            sanctified=False,
            original_name="HAUNTED REFUGE ESCALATION SIGIL",
        ),
    ),
    # Regular sigil
    (
        [
            "Nightmare Sigil",
            "Transform this dungeon into. aNightmare Dungeon",
            "Mercys Reach in Fractured Peaks",
            "DUNGEON AFFIXES",
            "Hidden Armory",
            "Exceptional items are kept here, granting elite monsters a powerful loot affix.",
            "Deathly Shadows",
            "Killing a monster has a chance to unleash a volatile pulse after a short delay, dealing heavy area damage.",
            "Account Bound",
            "Sell Value: 1 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(max_value=None, min_value=None, name="hidden_armory", text="", type=AffixType.normal, value=None),
                Affix(
                    max_value=None, min_value=None, name="deathly_shadows", text="", type=AffixType.normal, value=None
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_chaos=False,
            is_in_shop=False,
            item_type=ItemType.Sigil,
            name="mercys_reach",
            power=None,
            rarity=ItemRarity.Common,
            sanctified=False,
        ),
    ),
]


@pytest.mark.parametrize(("input_item", "expected_item"), items)
def test_items(input_item: list[str], expected_item: Item):
    src.tts.LAST_ITEM = input_item
    item = read_descr()
    assert item == expected_item
