import pytest

import src.tts
from src.item.data.affix import Affix, AffixType
from src.item.data.aspect import Aspect
from src.item.data.item_type import ItemType
from src.item.data.rarity import ItemRarity
from src.item.descr.read_descr_tts import read_descr
from src.item.models import Item

items = [
    (
        # In season 13 weapons have nothing we'd consider an inherent
        [
            "VICTORY SPINE",
            "Rare Sword",
            "850 Item Power",
            "1,406 Damage Per Second (-26)",
            "[1,023 - 1,535] Damage per Hit",
            "1.10 Attacks per Second (Fast)",
            "+1,802 Maximum Life [1,526 - 1,830]",
            "x7% All Damage Multiplier [6 - 10]%",
            "x24% Critical Strike Damage Multiplier [13 - 25]%",
            "Lucky Hit: Up to a 15% Chance to Restore +4 Primary Resource [3 - 4]",
            "Requires Level 70. Account Bound",
            "Sell Value: 13,381 Gold",
            "Durability: 100/100. Tempers: 1/1",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=1830.0,
                    min_value=1526.0,
                    name="maximum_life",
                    text="+1,802 Maximum Life [1,526 - 1,830]",
                    type=AffixType.normal,
                    value=1802.0,
                ),
                Affix(
                    max_value=10.0,
                    min_value=6.0,
                    name="all_damage_multiplier",
                    text="x7% All Damage Multiplier [6 - 10]%",
                    type=AffixType.normal,
                    value=7.0,
                ),
                Affix(
                    max_value=25.0,
                    min_value=13.0,
                    name="critical_strike_damage_multiplier",
                    text="x24% Critical Strike Damage Multiplier [13 - 25]%",
                    type=AffixType.normal,
                    value=24.0,
                ),
                Affix(
                    max_value=4.0,
                    min_value=3.0,
                    name="lucky_hit_up_to_a_chance_to_restore_primary_resource",
                    text="Lucky Hit: Up to a 15% Chance to Restore +4 Primary Resource [3 - 4]",
                    type=AffixType.normal,
                    value=4.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Sword,
            name="victory_spine",
            original_name="VICTORY SPINE",
            power=850,
            rarity=ItemRarity.Rare,
            seasonal_attribute=None,
        ),
    ),
    # Boots also lost their inherents and Evade grants whatever for 1.5 seconds was being read as a GA
    (
        [
            "MARCH INCEPTION",
            "Rare Boots",
            "850 Item Power",
            "638 Armor (-8.8% Toughness)",
            "+933 Armor [780 - 980]",
            "+22% Movement Speed [20 - 24]%",
            "+439 Shadow Resistance [416 - 523]",
            "Evade Grants +114% Movement Speed for 1.5 Seconds [100 - 125]%[1.5]",
            "Requires Level 70",
            "Sell Value: 10,705 Gold",
            "Durability: 100/100. Tempers: 1/1",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=980.0,
                    min_value=780.0,
                    name="armor",
                    text="+933 Armor [780 - 980]",
                    type=AffixType.normal,
                    value=933.0,
                ),
                Affix(
                    max_value=24.0,
                    min_value=20.0,
                    name="movement_speed",
                    text="+22% Movement Speed [20 - 24]%",
                    type=AffixType.normal,
                    value=22.0,
                ),
                Affix(
                    max_value=523.0,
                    min_value=416.0,
                    name="shadow_resistance",
                    text="+439 Shadow Resistance [416 - 523]",
                    type=AffixType.normal,
                    value=439.0,
                ),
                Affix(
                    max_value=125.0,
                    min_value=100.0,
                    name="evade_grants_movement_speed_for_seconds",
                    text="Evade Grants +114% Movement Speed for 1.5 Seconds [100 - 125]%[1.5]",
                    type=AffixType.normal,
                    value=114.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Boots,
            name="march_inception",
            original_name="MARCH INCEPTION",
            power=850,
            rarity=ItemRarity.Rare,
            seasonal_attribute=None,
        ),
    ),
    # This is just to ensure 3 affix rares still work
    (
        [
            "RIP NEXUS",
            "Rare Sword",
            "850 Item Power",
            "1,406 Damage Per Second (-26)",
            "[1,023 - 1,535] Damage per Hit",
            "1.10 Attacks per Second (Fast)",
            "+126 Dexterity +[125 - 149]",
            "+1,759 Maximum Life [1,526 - 1,830]",
            "x8% All Damage Multiplier [6 - 10]%",
            "Requires Level 70. Account Bound. Lord of Hatred Item",
            "Sell Value: 13,381 Gold",
            "Durability: 100/100. Tempers: 1/1",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=149.0,
                    min_value=125.0,
                    name="dexterity",
                    text="+126 Dexterity +[125 - 149]",
                    type=AffixType.normal,
                    value=126.0,
                ),
                Affix(
                    max_value=1830.0,
                    min_value=1526.0,
                    name="maximum_life",
                    text="+1,759 Maximum Life [1,526 - 1,830]",
                    type=AffixType.normal,
                    value=1759.0,
                ),
                Affix(
                    max_value=10.0,
                    min_value=6.0,
                    name="all_damage_multiplier",
                    text="x8% All Damage Multiplier [6 - 10]%",
                    type=AffixType.normal,
                    value=8.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Sword,
            name="rip_nexus",
            original_name="RIP NEXUS",
            power=850,
            rarity=ItemRarity.Rare,
            seasonal_attribute=None,
        ),
    ),
    # Shields also lost an inherent
    (
        [
            "CONCEITED DREAD SHIELD",
            "Legendary Shield",
            "767 Item Power",
            "863 Armor (-12.5% Toughness)",
            "20.0% Block Chance [20.0]%",
            "+100% Main Hand Weapon Damage [100]%",
            "+93 Strength +[85 - 102] (-11)",
            "+514 Thorns [386 - 579] (+514)",
            "+7.0% Healing Received [7.0 - 11.0]% (+7.0%)",
            "8.8% Damage Reduction [7.0 - 11.0]% (-1.8%)",
            "Deal 50%[x] [40 - 55]% increased damage while you have a Barrier active.",
            "Empty Socket",
            "Properties lost when equipped:",
            "+6.0% Critical Strike Chance",
            "Rampage: +6.0% Cooldown Reduction per Kill Streak Tier",
            "+100 All Stats",
            "+668 Maximum Life",
            "Legendary Power",
            "Requires Level 60",
            "Sell Value: 26,829 Gold",
            "Durability: 100/100. Tempers: 3/3",
            "Mousewheel scroll down",
            "Scroll Down",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=102.0,
                    min_value=85.0,
                    name="strength",
                    text="+93 Strength +[85 - 102] (-11)",
                    type=AffixType.normal,
                    value=93.0,
                ),
                Affix(
                    max_value=579.0,
                    min_value=386.0,
                    name="thorns",
                    text="+514 Thorns [386 - 579] (+514)",
                    type=AffixType.normal,
                    value=514.0,
                ),
                Affix(
                    max_value=11.0,
                    min_value=7.0,
                    name="healing_received",
                    text="+7.0% Healing Received [7.0 - 11.0]% (+7.0%)",
                    type=AffixType.normal,
                    value=7.0,
                ),
                Affix(
                    max_value=11.0,
                    min_value=7.0,
                    name="damage_reduction",
                    text="8.8% Damage Reduction [7.0 - 11.0]% (-1.8%)",
                    type=AffixType.normal,
                    value=8.8,
                ),
            ],
            aspect=Aspect(
                name="conceited", text="Deal 50%[x] [40 - 55]% increased damage while you have a Barrier active."
            ),
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Shield,
            name="conceited_dread_shield",
            original_name="CONCEITED DREAD SHIELD",
            power=767,
            rarity=ItemRarity.Legendary,
            seasonal_attribute=None,
        ),
    ),
    # Magic item with 1 affix
    (
        [
            "FIERY RING",
            "Magic Ring",
            "274 Item Power",
            "38 All Resist",
            "x5% Fire Damage Multiplier [4 - 6]%",
            "Requires Level 26",
            "Sell Value: 1,107 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=6.0,
                    min_value=4.0,
                    name="fire_damage_multiplier",
                    text="x5% Fire Damage Multiplier [4 - 6]%",
                    type=AffixType.normal,
                    value=5.0,
                )
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Ring,
            name="fiery_ring",
            original_name="FIERY RING",
            power=274,
            rarity=ItemRarity.Magic,
            seasonal_attribute=None,
        ),
    ),
    # Magic item with 2 affixes that happens to be ancestral
    (
        [
            "CRIMSON REINFORCED CROSSBOW OF VENOM",
            "Ancestral Magic Crossbow",
            "900 Item Power",
            "3,794 Damage Per Second (-351)",
            "[3,448 - 4,984] Damage per Hit",
            "0.90 Attacks per Second (Slow)",
            "+378 Weapon Damage [230 - 383]",
            "x20% Poison Damage Multiplier [14 - 20]%",
            "Requires Level 70Rogue. Only",
            "Sell Value: 14,789 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=383.0,
                    min_value=230.0,
                    name="weapon_damage",
                    text="+378 Weapon Damage [230 - 383]",
                    type=AffixType.normal,
                    value=378.0,
                ),
                Affix(
                    max_value=20.0,
                    min_value=14.0,
                    name="poison_damage_multiplier",
                    text="x20% Poison Damage Multiplier [14 - 20]%",
                    type=AffixType.normal,
                    value=20.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Crossbow2H,
            name="crimson_reinforced_crossbow_of_venom",
            original_name="CRIMSON REINFORCED CROSSBOW OF VENOM",
            power=900,
            rarity=ItemRarity.Magic,
            seasonal_attribute=None,
        ),
    ),
    # Ancestral common
    (
        [
            "CROSSBOW",
            "Ancestral Crossbow",
            "900 Item Power",
            "3,454 Damage Per Second (-691)",
            "[3,070 - 4,606] Damage per Hit",
            "0.90 Attacks per Second (Slow)",
            "Requires Level 70Rogue. Only",
            "Sell Value: 8,873 Gold",
            "Durability: 100/100",
            "Right mouse button",
        ],
        Item(
            affixes=[],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Crossbow2H,
            name="crossbow",
            original_name="CROSSBOW",
            power=900,
            rarity=ItemRarity.Common,
            seasonal_attribute=None,
        ),
    ),
    # Rare seal
    (
        [
            "VIGOROUS HORADRIC SEAL OF DETERMINATION",
            "Rare Horadric Seal",
            "Unlocks 4 Charm Slots",
            "8.0% Maximum Life [6.5 - 8.0]% (+8.0%)",
            "Arms of Arreat:. +3 [2 - 3] maximum Resolve",
            "Properties lost when equipped:",
            "Unlocks 2 Charm Slots",
            "+7.5% Resistance to All Elements",
            "Seal Power",
            "Seal Power",
            "Requires Level 70. Lord of Hatred Item",
            "Sell Value: 1,340,759 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=8.0,
                    min_value=6.5,
                    name="maximum_life",
                    text="8.0% Maximum Life [6.5 - 8.0]% (+8.0%)",
                    type=AffixType.normal,
                    value=8.0,
                ),
                Affix(
                    max_value=3.0,
                    min_value=2.0,
                    name="arms_of_arreat_maximum_resolve",
                    text="Arms of Arreat:. +3 [2 - 3] maximum Resolve",
                    type=AffixType.normal,
                    value=3.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.HoradricSeal,
            name="vigorous_horadric_seal_of_determination",
            original_name="VIGOROUS HORADRIC SEAL OF DETERMINATION",
            power=None,
            rarity=ItemRarity.Rare,
            seasonal_attribute=None,
            set=None,
        ),
    ),
    # Legendary seal with multiple affixes
    (
        [
            "RESISTANT HORADRIC SEAL OF CURRENT",
            "Legendary Horadric Seal",
            "Unlocks 5 Charm Slots",
            "+8.5% Resistance to All Elements [7.5 - 10.0]%",
            "Cains Wild Lighting:. +3 [3 - 4] Mana per Second",
            "Tal Rashas Threefold Way:. +3 [2 - 3] to Ball Lightning",
            "Requires Level 50. Lord of Hatred Item",
            "Sell Value: 13,380,834 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=10.0,
                    min_value=7.5,
                    name="resistance_to_all_elements",
                    text="+8.5% Resistance to All Elements [7.5 - 10.0]%",
                    type=AffixType.normal,
                    value=8.5,
                ),
                Affix(
                    max_value=4.0,
                    min_value=3.0,
                    name="cains_wild_lightning_mana_per_second",
                    text="Cains Wild Lighting:. +3 [3 - 4] Mana per Second",
                    type=AffixType.normal,
                    value=3.0,
                ),
                Affix(
                    max_value=3.0,
                    min_value=2.0,
                    name="tal_rashas_threefold_way_to_ball_lightning",
                    text="Tal Rashas Threefold Way:. +3 [2 - 3] to Ball Lightning",
                    type=AffixType.normal,
                    value=3.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.HoradricSeal,
            name="resistant_horadric_seal_of_current",
            original_name="RESISTANT HORADRIC SEAL OF CURRENT",
            power=None,
            rarity=ItemRarity.Legendary,
            seasonal_attribute=None,
            set=None,
        ),
    ),
    # Legendary seal with +1 charm slot
    (
        [
            "RESISTANT HORADRIC SEAL OF GLORY",
            "Legendary Horadric Seal",
            "Unlocks 6 Charm Slots",
            "+7.5% Resistance to All Elements [7.5 - 10.0]%",
            "Sescherons Fury:. +8% [7 - 11]% Damage Reduction",
            "+1 Charm Slot",
            "Requires Level 50. Lord of Hatred Item",
            "Sell Value: 13,386,186 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=10.0,
                    min_value=7.5,
                    name="resistance_to_all_elements",
                    text="+7.5% Resistance to All Elements [7.5 - 10.0]%",
                    type=AffixType.normal,
                    value=7.5,
                ),
                Affix(
                    max_value=11.0,
                    min_value=7.0,
                    name="sescherons_fury_damage_reduction",
                    text="Sescherons Fury:. +8% [7 - 11]% Damage Reduction",
                    type=AffixType.normal,
                    value=8.0,
                ),
                Affix(
                    max_value=None,
                    min_value=None,
                    name="charm_slot",
                    text="+1 Charm Slot",
                    type=AffixType.normal,
                    value=1.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.HoradricSeal,
            name="resistant_horadric_seal_of_glory",
            original_name="RESISTANT HORADRIC SEAL OF GLORY",
            power=None,
            rarity=ItemRarity.Legendary,
            seasonal_attribute=None,
            set=None,
        ),
    ),
    # Magic charm
    (
        [
            "SKILLFUL CHARM",
            "Ancestral Magic Charm",
            "+2 to Basic Skills [2 - 3]",
            "Requires Level 70. Lord of Hatred Item",
            "Sell Value: 14,789 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=3.0,
                    min_value=2.0,
                    name="to_basic_skills",
                    text="+2 to Basic Skills [2 - 3]",
                    type=AffixType.normal,
                    value=2.0,
                )
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Charm,
            name="skillful_charm",
            original_name="SKILLFUL CHARM",
            power=None,
            rarity=ItemRarity.Magic,
            seasonal_attribute=None,
            set=None,
        ),
    ),
    # Rare charm
    (
        [
            "SPEEDY CHARM OF GREED",
            "Ancestral Rare Charm",
            "+7% Gold Drop Rate +[5 - 9]%",
            "+14% Movement Speed [13 - 16]%",
            "Requires Level 70. Lord of Hatred Item",
            "Sell Value: 150,843 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=9.0,
                    min_value=5.0,
                    name="gold_drop_rate",
                    text="+7% Gold Drop Rate +[5 - 9]%",
                    type=AffixType.normal,
                    value=7.0,
                ),
                Affix(
                    max_value=16.0,
                    min_value=13.0,
                    name="movement_speed",
                    text="+14% Movement Speed [13 - 16]%",
                    type=AffixType.normal,
                    value=14.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Charm,
            name="speedy_charm_of_greed",
            original_name="SPEEDY CHARM OF GREED",
            power=None,
            rarity=ItemRarity.Rare,
            seasonal_attribute=None,
            set=None,
        ),
    ),
    # Set Charm
    (
        [
            "MLOR OF SESCHERONS FURY",
            "Set Charm",
            "8.0% Maximum Life [6.5 - 8.0]%",
            "Lucky Hit: Up to a +4.0% Chance to Daze for 2 Seconds [3.0 - 4.0]%",
            "Sescherons Fury",
            "Phoba of Sescherons Fury",
            "Fer of Sescherons Fury",
            "Mlor of Sescherons Fury",
            "Linta of Sescherons Fury",
            "Berú of Sescherons Fury",
            "Sescherons Fury (5/5). (2) Set:. While at or above 100 Fury, you become Colossal, losing 50% Cast Speed but gaining 20% Character and Skill Size and 120%[x] increased damage.. (3) Set:. You gain an additional 10 Fury when hit and 30% Maximum Life.. (5) Set:. Your Maximum Fury is increased by 50. . Colossal further increases Skill size to 50%, and damage to 600%[x].",
            "Barbarian female—exhumed amidst the corpses of two-score Khazra, presumably killed by this female single-handed before she fell. Impaled by five spears. -Jered Cain, notes from Bear Tribe dig site",
            "Requires Level 70Barbarian. Only. Unique Equipped. Lord of Hatred Item",
            "Sell Value: 1,340,759 Gold",
            "Mousewheel scroll down",
            "Scroll Down",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=8.0,
                    min_value=6.5,
                    name="maximum_life",
                    text="8.0% Maximum Life [6.5 - 8.0]%",
                    type=AffixType.normal,
                    value=8.0,
                ),
                Affix(
                    max_value=4.0,
                    min_value=3.0,
                    name="lucky_hit_up_to_a_chance_to_daze_for_seconds",
                    text="Lucky Hit: Up to a +4.0% Chance to Daze for 2 Seconds [3.0 - 4.0]%",
                    type=AffixType.normal,
                    value=4.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Charm,
            name="mlor_of_sescherons_fury",
            original_name="MLOR OF SESCHERONS FURY",
            power=None,
            rarity=ItemRarity.Set,
            seasonal_attribute=None,
            set="sescherons_fury",
        ),
    ),
    # Set Charm with compare screen up which annoyingly makes it difficult to find the set
    (
        [
            "FER OF SESCHERONS FURY",
            "Set Charm",
            "+166 Fire Resistance [165 - 210] (+166)",
            "+2 to Combat Skills [1 - 2] (+2)",
            "Properties lost when equipped:",
            "Lucky Hit: Up to a +1.0% Chance to Daze for 2 Seconds",
            "+4.0% Total Armor",
            "Sescherons Fury",
            "Phoba of Sescherons Fury",
            "Fer of Sescherons Fury",
            "Mlor of Sescherons Fury",
            "Linta of Sescherons Fury",
            "Berú of Sescherons Fury",
            "Sescherons Fury (5/5). (2) Set:. While at or above 100 Fury, you become Colossal, losing 50% Cast Speed but gaining 20% Character and Skill Size and 120%[x] increased damage.. (3) Set:. You gain an additional 10 Fury when hit and 30% Maximum Life.. (5) Set:. Your Maximum Fury is increased by 50. . Colossal further increases Skill size to 50%, and damage to 600%[x].",
            "Barbarian female—exhumed amidst the corpses of two-score Khazra, presumably killed by this female single-handed before she fell. Impaled by five spears. -Jered Cain, notes from Bear Tribe dig site",
            "Requires Level 42Barbarian. Only. Unique Equipped. Lord of Hatred Item",
            "Sell Value: 457,819 Gold",
            "Mousewheel scroll down",
            "Scroll Down",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=210.0,
                    min_value=165.0,
                    name="fire_resistance",
                    text="+166 Fire Resistance [165 - 210] (+166)",
                    type=AffixType.normal,
                    value=166.0,
                ),
                Affix(
                    max_value=2.0,
                    min_value=1.0,
                    name="to_combat_skills",
                    text="+2 to Combat Skills [1 - 2] (+2)",
                    type=AffixType.normal,
                    value=2.0,
                ),
            ],
            aspect=None,
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Charm,
            name="fer_of_sescherons_fury",
            original_name="FER OF SESCHERONS FURY",
            power=None,
            rarity=ItemRarity.Set,
            seasonal_attribute=None,
            set="sescherons_fury",
        ),
    ),
    # Unique charm
    (
        [
            "TUSKHELM OF JORITZ THE MIGHTY",
            "Unique Charm",
            "+486 Cold Resistance [416 - 523]",
            "Lucky Hit: Up to a 40% Chance to Deal +950 Physical Damage [550 - 1,000]",
            "When you gain Berserking while already Berserk, you become more enraged granting 48%[x] [40 - 50]% increased damage, 6 Fury per second, and 10% Cooldown Reduction.",
            "As he fought with side by side with Raekor to liberate the labor camp, Joritz claimed this dented helm from a fallen foe. As his legend grew, its unique shape became synonymous with his great deeds.",
            "Requires Level 70Barbarian. Only. Unique Equipped. Lord of Hatred Item",
            "Sell Value: 8,033,852 Gold",
            "Right mouse button",
        ],
        Item(
            affixes=[
                Affix(
                    max_value=523.0,
                    min_value=416.0,
                    name="cold_resistance",
                    text="+486 Cold Resistance [416 - 523]",
                    type=AffixType.normal,
                    value=486.0,
                ),
                Affix(
                    max_value=1000.0,
                    min_value=550.0,
                    name="lucky_hit_up_to_a_chance_to_deal_physical_damage",
                    text="Lucky Hit: Up to a 40% Chance to Deal +950 Physical Damage [550 - 1,000]",
                    type=AffixType.normal,
                    value=950.0,
                ),
            ],
            aspect=Aspect(
                name="tuskhelm_of_joritz_the_mighty",
                min_value=40.0,
                max_value=50.0,
                text="When you gain Berserking while already Berserk, you become more enraged granting 48%[x] [40 - 50]% increased damage, 6 Fury per second, and 10% Cooldown Reduction.",
                value=48.0,
            ),
            codex_upgrade=False,
            cosmetic_upgrade=False,
            inherent=[],
            is_in_shop=False,
            item_type=ItemType.Charm,
            name="tuskhelm_of_joritz_the_mighty",
            original_name="TUSKHELM OF JORITZ THE MIGHTY",
            power=None,
            rarity=ItemRarity.Unique,
            seasonal_attribute=None,
            set=None,
        ),
    ),
]


@pytest.mark.parametrize(("input_item", "expected_item"), items)
def test_items(input_item: list[str], expected_item: Item):
    src.tts.LAST_ITEM = input_item
    item = read_descr()
    assert item == expected_item
