name: Setup env

description: This action sets up a conda environment with Mambaforge and installs dependencies from an environment.yml file.

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"

    - name: Setup uv
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
        enable-cache: true
        ignore-nothing-to-cache: true

    - name: Install dependencies
      shell: powershell
      run: uv pip install -r requirements.txt
