name: Setup env

description: This action sets up a conda environment with Mambaforge and installs dependencies from an environment.yml file.

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        cache: "pip"

    - name: Install dependencies
      shell: powershell
      run: python.exe -m pip install -r requirements.txt
